/*
 * imca.h
 * 
 * Part of dft2lnt library - a library containing read/write operations for DFT
 * files in Galileo format and translating DFT specifications into Lotos NT.
 * 
 * @author Dennis Guck
 */

#ifndef IMCA_H
#define IMCA_H

#include "FileSystem.h"
#include <vector>

class IMCA {
public:

	typedef double T_Chance;
	static double T_Chance_Default;

	class FileHandler {
	private:
		std::vector<std::pair<std::string,T_Chance>> results;
		bool i_isCalculated;
		std::string i_calcCommand;
		T_Chance result;
	public:
		
		FileHandler(std::string calcCommand):
			i_isCalculated(false),
			i_calcCommand(calcCommand),
			result(T_Chance_Default) {
		}
		
		/**
		 * Read the result from the specified IMCA output file.
		 * Use this for IMCA output that is the result of an IMCA input file
		 * generated by the SAME or equivalent object.
		 * Obtain the result with getResult().
		 * @param file The IMCA output file in which the result can be found.
		 */
		virtual int readOutputFile(const File& file);
		
		/**
		 * Return the result previously read with readOutputFile().
		 * @return The result of the calculation.
		 */
		virtual T_Chance getResult();

		virtual std::vector<std::pair<std::string,T_Chance>> getResults();
	};
};

#endif
