#ifndef MRMC_H
#define MRMC_H

#include "FileSystem.h"
#include <vector>

class MRMC {
public:

	typedef float T_Chance;
	static float T_Chance_Default;

	class FileHandler {
	private:
		std::vector<T_Chance> results;
		bool m_isCalculated;
		T_Chance result;
	public:
	
		/**
		 * Generate an MRMC input file according to the given specifications
		 * @param file Generated contents will be written to this file.
		 */
		virtual int generateInputFile(const File& file);
		
		/**
		 * Read the result from the specified MRMC output file.
		 * Use this for MRMC output that is the result of an MRMC input file
		 * generated by the SAME or equivalent object.
		 * Obtain the result with getResult().
		 * @param file The MRMC output file in which the result can be found.
		 */
		virtual int readOutputFile(const File& file);
		
		/**
		 * Return the result previously read with readOutputFile().
		 * @return The result of the calculation.
		 */
		virtual T_Chance getResult();
	};
};

#endif