/*
 * mrmc.h
 * 
 * Part of dft2lnt library - a library containing read/write operations for DFT
 * files in Galileo format and translating DFT specifications into Lotos NT.
 * 
 * @author Freark van der Berg
 */

#ifndef MRMC_H
#define MRMC_H

#include "FileSystem.h"
#include <vector>

class MRMC {
public:

	typedef double T_Chance;
	static double T_Chance_Default;

	class FileHandler {
	private:
		std::vector<T_Chance> results;
		bool m_isCalculated;
		std::string m_calcCommand;
		T_Chance result;
	public:
		
		FileHandler(std::string calcCommand):
			m_isCalculated(false),
			m_calcCommand(calcCommand),
			result(T_Chance_Default) {
		}
		
		/**
		 * Generate an MRMC input file according to the given specifications
		 * @param file Generated contents will be written to this file.
		 */
		virtual int generateInputFile(const File& file);
		
		/**
		 * Read the result from the specified MRMC output file.
		 * Use this for MRMC output that is the result of an MRMC input file
		 * generated by the SAME or equivalent object.
		 * Obtain the result with getResult().
		 * @param file The MRMC output file in which the result can be found.
		 */
		virtual int readOutputFile(const File& file);
		
		/**
		 * Return the result previously read with readOutputFile().
		 * @return The result of the calculation.
		 */
		virtual T_Chance getResult();
	};
};

#endif