/*
 * mrmc.h
 * 
 * Part of dft2lnt library - a library containing read/write operations for DFT
 * files in Galileo format and translating DFT specifications into Lotos NT.
 * 
 * @author Freark van der Berg
 */

#ifndef MRMC_H
#define MRMC_H

#include "FileSystem.h"
#include "decnumber.h"
#include <vector>

class MRMCParser {
private:
	std::vector<std::pair<decnumber<>, decnumber<>>> results;
	bool m_isCalculated;
	std::string m_calcCommand;
public:
	
	MRMCParser(std::string calcCommand):
		m_isCalculated(false),
		m_calcCommand(calcCommand) {
	}
	
	/**
	 * Generate an MRMC input file according to the given specifications
	 * @param file Generated contents will be written to this file.
	 */
	int generateInputFile(const File& file);
	
	/**
	 * Read the result from the specified MRMC output file.
	 * Use this for MRMC output that is the result of an MRMC input file
	 * generated by the SAME or equivalent object.
	 * Obtain the result with getResult().
	 * @param file The MRMC output file in which the result can be found.
	 */
	int readOutputFile(const File& file);
	
	/**
	 * Return the result previously read with readOutputFile().
	 * @return The result of the calculation.
	 */
	std::pair<decnumber<>, decnumber<>> getResult();
};

#endif
