name: Compile and Test on MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Install dependencies
      run: brew install bison flex yaml-cpp gsl
    - name: Set environment variables
      run: |
        echo "NUMCORES=$(system_profiler SPHardwareDataType | grep 'Number of Cores' | grep -o '[[:digit:]]\+')" > $GITHUB_ENV
        echo /usr/local/opt/bison/bin >> $GITHUB_PATH
        echo /usr/local/opt/flex/bin >> $GITHUB_PATH
        echo ${{github.workspace}}/imrmc/bin >> $GITHUB_PATH
        echo ${{github.workspace}}/dftroot/bin >> $GITHUB_PATH
    - name: Prepare to build DFTCalc
      run: mkdir build && cd build && cmake -DDFTROOT=$GITHUB_WORKSPACE/dftroot ..
    - name: Compile DFTCalc
      run: cd build && make -j$NUMCORES install
    - name: Checkout DFTRES
      uses: actions/checkout@v3
      with:
        repository: utwente-fmt/DFTRES
        path: DFTRES
    - name: Get cache revisions
      id: cache-revs
      run: |
        cd DFTRES && echo "dftres=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "imrmc=$(git ls-remote git://git.ennoruijters.nl/imrmc.git | grep '\srefs/heads/master$' | grep -o '^[0-9a-z]\+')" >> $GITHUB_OUTPUT
    - name: Cache DFTRES
      id: cache-dftres
      uses: actions/cache@v3
      with:
        path: DFTRES/DFTRES.jar
        key: ${{ runner.os }}-dftres-${{ steps.cache-revs.outputs.dftres }}
    - name: Compile DFTRES if needed
      if: steps.cache-dftres.outputs.cache-hit != 'true'
      run: cd DFTRES && make jar
    - name: Cache IMRMC
      id: cache-imrmc
      uses: actions/cache@v3
      with:
        path: imrmc/bin/imrmc
        key: ${{ runner.os }}-imrmc-${{ steps.cache-revs.outputs.imrmc }}
    - name: Checkout IMRMC
      if: steps.cache-imrmc.outputs.cache-hit != 'true'
      run: git clone --depth 1 git://git.ennoruijters.nl/imrmc.git imrmc
    - name: Compile IMRMC
      if: steps.cache-imrmc.outputs.cache-hit != 'true'
      run: cd imrmc && make all -j$NUMCORES
    - name: Tests
      env:
        DFTRES: ${{github.workspace}}/DFTRES
      run: cd test && bash test.sh --exact --imrmc
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: test-results
        path: test/output
